name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev xorg-dev

    - name: Extract version
      id: get_version
      run: |
        version=$(grep -oP 'psw v\K[0-9.]+' ./cmd/version.go)
        echo "version=${version}" >> $GITHUB_ENV

    - name: Build Applications
      run: |
        make build

    - name: Generate SHA256 Checksums
      run: |
        cd ./bin
        sha256sum psw > psw.sha256
        sha256sum clipclean > clipclean.sha256

    - name: Create GitHub Release and Upload Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: v${{ env.version }}
      run: |
        gh release create $VERSION ./bin/psw ./bin/psw.sha256 ./bin/clipclean ./bin/clipclean.sha256 \
          --title "Release $VERSION" \
          --notes "Release of psw and clipclean binaries."

